/**
 * English translations for 365 daily encouragement quotes.
 * Source: 365-励志名言.md
 * Generated from curated translations — Peterson rules use original English;
 * Western sources use original English; Chinese classics use standard literary English.
 */

export const enByQuote = new Map([
  ["笔直站立，昂首挺胸。", "Stand up straight with your shoulders back."],
  ["像对待你有责任帮助的人那样对待自己。", "Treat yourself like someone you are responsible for helping."],
  ["与真心希望你好的人做朋友，远离损友。", "Make friends with people who want the best for you."],
  ["和昨天的自己比，别和今天的别人比。", "Compare yourself to who you were yesterday, not to who someone else is today."],
  ["别让孩子做出令你讨厌他的事。", "Do not let your children do anything that makes you dislike them."],
  ["批判世界之前先清理你的房间。", "Set your house in perfect order before you criticize the world."],
  ["追求意义而非权宜。", "Pursue what is meaningful (not what is expedient)."],
  ["说真话，或至少别撒谎。", "Tell the truth — or, at least, don't lie."],
  ["假设聆听的人可能知道你不知道的事。", "Assume that the person you are listening to might know something you don't."],
  ["言辞精确，直面问题。", "Be precise in your speech."],
  ["不要打扰正在玩滑板的孩子。", "Do not bother children when they are skateboarding."],
  ["在路上遇到猫时摸摸它。", "Pet a cat when you encounter one on the street."],
  ["不要草率贬损社会制度与创造性成就。", "Do not carelessly denigrate social institutions and creative achievement."],
  ["想象你能成为谁，然后专注地朝那个方向努力。", "Imagine who you could be, and then aim single-mindedly at that."],
  ["不要把不想面对的事藏在迷雾中。", "Do not hide unwanted things in the fog."],
  ["留意责任被推卸之处潜藏的机会。", "Notice that opportunity lurks where responsibility has been abdicated."],
  ["勿行你所憎之事。", "Do not do what you hate."],
  ["抛弃意识形态盲从。", "Abandon ideology."],
  ["至少在一件事上竭尽全力，看会发生什么。", "Work as hard as you possibly can on at least one thing and see what happens."],
  ["试着把家里的一个房间布置得尽可能美。", "Try to make one room in your home as beautiful as possible."],
  ["旧记忆仍困扰你，就仔细完整地写下来。", "If old memories still upset you, write them down carefully and completely."],
  ["用心经营关系中的浪漫。", "Plan and work diligently to maintain the romance in your relationship."],
  ["不要让自己变得怨恨、欺诈或傲慢。", "Do not allow yourself to become resentful, deceitful, or arrogant."],
  ["尽管受苦，仍要心怀感恩。", "Be grateful in spite of your suffering."],
  ["你值得幸福的生活。", "You deserve a happy life."],
  ["天生我材必有用。", "Heaven gave me talents; they must serve a purpose."],
  ["长风破浪会有时，直挂云帆济沧海。", "A time will come to cleave the waves and set sail for the vast sea."],
  ["生活不是等待暴风雨过去，而是学会在雨中跳舞。", "Life is not about waiting for the storm to pass, but learning to dance in the rain."],
  ["相信自己，你比想象中更强大。", "Believe in yourself — you are stronger than you think."],
  ["每一次跌倒，都是为了更好地站起来。", "Every fall is so you can stand up stronger."],
  ["你的存在本身就是一种价值。", "Your existence itself is valuable."],
  ["不要害怕慢，只怕停。", "Don't fear going slow; fear stopping."],
  ["今天的努力，是明天的底气。", "Today's effort is tomorrow's confidence."],
  ["你远比自己认为的更有能力。", "You are far more capable than you believe."],
  ["困难是成长的阶梯。", "Difficulty is the ladder of growth."],
  ["保持热爱，奔赴山海。", "Keep your passion and journey toward distant horizons."],
  ["你配得上所有美好。", "You deserve all that is good."],
  ["星光不问赶路人，时光不负有心人。", "The stars do not ask who hurries; time rewards those who persevere."],
  ["做自己的太阳，无需借谁的光。", "Be your own sun; you need no borrowed light."],
  ["人生没有白走的路，每一步都算数。", "No step in life is wasted; every one counts."],
  ["你的潜力无限，别给自己设限。", "Your potential is limitless — do not limit yourself."],
  ["允许自己休息，但别放弃。", "Allow yourself to rest, but do not give up."],
  ["你正在成为你想成为的人。", "You are becoming the person you want to be."],
  ["慢慢来，比较快。", "Slow and steady wins the race."],
  ["每一次尝试都值得骄傲。", "Every attempt is worth being proud of."],
  ["你的感受很重要，你的声音值得被听见。", "Your feelings matter, and your voice deserves to be heard."],
  ["不必完美，只需真实。", "You need not be perfect — only authentic."],
  ["你已经做得很好了。", "You are already doing well."],
  ["明天又是新的一天。", "Tomorrow is a new day."],
  ["你的努力，时间会看见。", "Time will see your effort."],
  ["相信自己，一切皆有可能。", "Believe in yourself — anything is possible."],
  ["你值得被爱，也值得爱自己。", "You deserve to be loved, and to love yourself."],
  ["坚持下去，美好正在路上。", "Keep going — good things are on the way."],
  ["人不是为失败而生的。", "A man is not made for defeat."],
  ["一个人可以被毁灭，但不能被打败。", "A man can be destroyed but not defeated."],
  ["冬天来了，春天还会远吗？", "If winter comes, can spring be far behind?"],
  ["希望是美好的，也许是人间至善，而美好的事物永不消逝。", "Hope is a good thing, maybe the best of things, and no good thing ever dies."],
  ["有些鸟儿是关不住的，它们的每一片羽毛都闪耀着自由的光辉。", "Some birds are not meant to be caged; every feather shines with the light of freedom."],
  ["生命在于奋斗。", "Life consists in struggle."],
  ["世界上只有一种英雄主义，那就是在认清生活真相之后依然热爱生活。", "There is only one heroism in the world: to see the world as it is and to love it."],
  ["你不需要很厉害才开始，但你需要开始才能很厉害。", "You don't need to be great to start, but you need to start to be great."],
  ["每一个不曾起舞的日子，都是对生命的辜负。", "Every day you do not dance is a day wasted."],
  ["杀不死我的，会让我更强大。", "What does not kill me makes me stronger."],
  ["成为你自己。", "Become who you are."],
  ["你的价值不取决于他人的评价。", "Your worth does not depend on others' opinions."],
  ["勇敢不是不害怕，而是害怕却依然前行。", "Courage is not the absence of fear, but acting despite it."],
  ["你拥有改变自己的力量。", "You have the power to change yourself."],
  ["善待自己，就像善待你最爱的人。", "Treat yourself as kindly as you would someone you love most."],
  ["你的故事才刚刚开始。", "Your story has only just begun."],
  ["别让别人定义你的可能。", "Do not let others define what is possible for you."],
  ["小步前进，也是前进。", "Small steps forward are still forward."],
  ["你值得拥有平静与喜悦。", "You deserve peace and joy."],
  ["放下完美主义，拥抱进步。", "Let go of perfectionism and embrace progress."],
  ["你的努力不会白费。", "Your effort will not be in vain."],
  ["每一次呼吸都是新的开始。", "Every breath is a fresh start."],
  ["你比昨天更好。", "You are better than yesterday."],
  ["允许自己不完美，但别停止成长。", "Allow yourself to be imperfect, but never stop growing."],
  ["你的内心比你想象的更坚韧。", "Your inner strength is greater than you imagine."],
  ["相信过程，相信时间。", "Trust the process; trust time."],
  ["你是自己最好的朋友。", "You are your own best friend."],
  ["今天，选择对自己温柔。", "Today, choose to be gentle with yourself."],
  ["满招损，谦受益。", "Pride brings loss; humility brings gain."],
  ["天行健，君子以自强不息。", "As heaven moves with vigor, the noble person strives unceasingly."],
  ["地势坤，君子以厚德载物。", "As earth is receptive, the noble person bears the world with virtue."],
  ["不积跬步，无以至千里。", "Without accumulating small steps, one cannot reach a thousand li."],
  ["不积小流，无以成江海。", "Without gathering small streams, there can be no rivers or seas."],
  ["锲而不舍，金石可镂。", "Perseverance can carve even metal and stone."],
  ["千里之行，始于足下。", "A journey of a thousand miles begins with a single step."],
  ["胜人者有力，自胜者强。", "To conquer others takes strength; to conquer yourself is true power."],
  ["知人者智，自知者明。", "To know others is wisdom; to know yourself is enlightenment."],
  ["你不需要向任何人证明什么。", "You owe no one proof of your worth."],
  ["你的节奏就是最好的节奏。", "Your pace is the right pace."],
  ["休息不是偷懒，是必要的充电。", "Rest is not laziness — it is necessary recharging."],
  ["你的感受是真实的，也是重要的。", "Your feelings are real and they matter."],
  ["每一次坚持都是对自己的承诺。", "Every act of persistence is a promise to yourself."],
  ["你值得拥有你想要的生活。", "You deserve the life you want."],
  ["别急，花开需要时间。", "Be patient — flowers need time to bloom."],
  ["你已经走了很远的路。", "You have already come a long way."],
  ["你的存在让世界更美好。", "Your presence makes the world better."],
  ["做对的事，而不是容易的事。", "Do what is right, not what is easy."],
  ["你的善良需要有锋芒。", "Your kindness needs boundaries."],
  ["边界感是爱自己的开始。", "Boundaries are where self-love begins."],
  ["说不也是一种能力。", "Saying no is also a skill."],
  ["你的时间很宝贵，别浪费在不对的人和事上。", "Your time is precious — do not waste it on the wrong people or things."],
  ["优先照顾好自己的需求。", "Put your own needs first."],
  ["你不需要取悦所有人。", "You do not need to please everyone."],
  ["真实的你，已经足够好。", "The real you is already enough."],
  ["接纳自己的全部，包括不完美。", "Accept all of yourself, including your imperfections."],
  ["你的价值不需要外部验证。", "Your worth needs no external validation."],
  ["内在的力量比外在的认可更重要。", "Inner strength matters more than outward approval."],
  ["今天，为自己而活。", "Today, live for yourself."],
  ["读书破万卷，下笔如有神。", "Read ten thousand books, and writing flows like divine inspiration."],
  ["会当凌绝顶，一览众山小。", "I shall ascend the highest peak and look down on all lesser mountains."],
  ["沉舟侧畔千帆过，病树前头万木春。", "Beside a sunken boat, a thousand sails pass; before a sick tree, ten thousand thrive in spring."],
  ["山重水复疑无路，柳暗花明又一村。", "Winding mountains and rivers — then willows shade and flowers bloom in another village."],
  ["纸上得来终觉浅，绝知此事要躬行。", "Book learning alone feels shallow; true knowledge comes from doing."],
  ["宝剑锋从磨砺出，梅花香自苦寒来。", "A sharp sword is forged through grinding; plum blossoms gain their fragrance from bitter cold."],
  ["不经一番寒彻骨，怎得梅花扑鼻香。", "Without bone-chilling cold, how could plum blossoms fill the air with fragrance?"],
  ["欲穷千里目，更上一层楼。", "To see a thousand miles further, climb one story higher."],
  ["海内存知己，天涯若比邻。", "A true friend at heart makes distance feel like next door."],
  ["莫愁前路无知己，天下谁人不识君。", "Fear not the road ahead without companions — who in the world does not know you?"],
  ["天生我材必有用，千金散尽还复来。", "Heaven gave me talents that must serve a purpose; gold spent will return again."],
  ["仰天大笑出门去，我辈岂是蓬蒿人。", "Laughing skyward as I go out the door — we are not meant to wither in the weeds."],
  ["你的梦想值得被认真对待。", "Your dreams deserve to be taken seriously."],
  ["别让小恐惧阻挡大梦想。", "Do not let small fears block big dreams."],
  ["你的热情是宝贵的财富。", "Your passion is a precious treasure."],
  ["保持好奇，保持探索。", "Stay curious; keep exploring."],
  ["学习是一辈子的事。", "Learning is a lifelong pursuit."],
  ["成长比成功更重要。", "Growth matters more than success."],
  ["你的进步值得庆祝。", "Your progress deserves celebration."],
  ["别和过去的自己比较。", "Do not compare yourself to your past self in judgment."],
  ["专注当下，就是最好的投资。", "Focus on the present — it is the best investment."],
  ["你的注意力是你最宝贵的资源。", "Your attention is your most precious resource."],
  ["选择把精力放在重要的事上。", "Choose to put your energy into what matters."],
  ["少即是多。", "Less is more."],
  ["质量比数量重要。", "Quality matters more than quantity."],
  ["深度比广度重要。", "Depth matters more than breadth."],
  ["你的专注力是超能力。", "Your focus is a superpower."],
  ["一次只做一件事。", "Do one thing at a time."],
  ["慢下来，感受过程。", "Slow down and feel the process."],
  ["先天下之忧而忧，后天下之乐而乐。", "Be the first to worry about the world's troubles and the last to enjoy its joys."],
  ["不以物喜，不以己悲。", "Do not rejoice in external gain or grieve over personal loss."],
  ["人生自古谁无死，留取丹心照汗青。", "Since ancient times, who has not died? Leave a loyal heart to shine through history."],
  ["粉身碎骨浑不怕，要留清白在人间。", "I fear not being ground to dust — I seek to leave purity in this world."],
  ["苟利国家生死以，岂因祸福避趋之。", "If it serves the nation, I would face life and death — how could I flee fortune or misfortune?"],
  ["海纳百川，有容乃大。", "The sea accepts all rivers; greatness comes from tolerance."],
  ["壁立千仞，无欲则刚。", "A cliff stands a thousand ren high; without desire, one is unyielding."],
  ["为天地立心，为生民立命，为往圣继绝学，为万世开太平。", "To establish the heart of heaven and earth, secure the destiny of the people, continue the lost learning of sages, and open peace for all generations."],
  ["路漫漫其修远兮，吾将上下而求索。", "The road ahead is long and arduous; I will search high and low without ceasing."],
  ["亦余心之所善兮，虽九死其犹未悔。", "For what my heart holds dear, though I die nine times, I would not regret it."],
  ["你的坚持终将美好。", "Your persistence will lead to something beautiful."],
  ["别放弃，转机可能就在下一秒。", "Do not give up — the turning point may be a second away."],
  ["黑暗过后必有黎明。", "After darkness comes dawn."],
  ["你的韧性超乎想象。", "Your resilience exceeds your imagination."],
  ["困难是暂时的，成长是永久的。", "Hardship is temporary; growth is permanent."],
  ["每一次挑战都是机会。", "Every challenge is an opportunity."],
  ["你的适应能力很强。", "You adapt well."],
  ["变化是成长的催化剂。", "Change is the catalyst for growth."],
  ["拥抱不确定性。", "Embrace uncertainty."],
  ["灵活比固执更有力量。", "Flexibility is stronger than stubbornness."],
  ["学会与不完美共处。", "Learn to live with imperfection."],
  ["生活不需要完美，只需要真实。", "Life needs not perfection — only authenticity."],
  ["你的独特是你的优势。", "Your uniqueness is your advantage."],
  ["不必模仿别人，做最好的自己。", "Do not imitate others; be your best self."],
  ["你的视角是独一无二的。", "Your perspective is one of a kind."],
  ["世界需要你的声音。", "The world needs your voice."],
  ["你的贡献很重要。", "Your contribution matters."],
  ["别低估自己的影响力。", "Do not underestimate your influence."],
  ["小小的善举也能改变世界。", "Small acts of kindness can change the world."],
  ["你的存在本身就有意义。", "Your existence itself is meaningful."],
  ["知之为知之，不知为不知，是知也。", "To know what you know and know what you do not know — that is wisdom."],
  ["三人行，必有我师焉。", "When three walk together, one of them can be my teacher."],
  ["学而时习之，不亦说乎。", "To learn and practice from time to time — is that not a joy?"],
  ["己所不欲，勿施于人。", "Do not do to others what you would not want done to you."],
  ["君子坦荡荡，小人长戚戚。", "The noble person is open and at ease; the petty person is anxious and fretful."],
  ["知之者不如好之者，好之者不如乐之者。", "Those who know are not equal to those who love; those who love are not equal to those who delight in it."],
  ["温故而知新，可以为师矣。", "Review the old and learn the new — then one may be a teacher."],
  ["敏而好学，不耻下问。", "Quick to learn and unashamed to ask those below you."],
  ["见贤思齐焉，见不贤而内自省也。", "When you see the worthy, strive to equal them; when you see the unworthy, turn inward and examine yourself."],
  ["逝者如斯夫，不舍昼夜。", "It passes on like this, never ceasing day or night."],
  ["你的时间观决定你的人生。", "Your view of time shapes your life."],
  ["今天是你余生中最年轻的一天。", "Today is the youngest day of the rest of your life."],
  ["别等完美时机，现在就开始。", "Do not wait for the perfect moment — start now."],
  ["行动是治愈恐惧的良药。", "Action is the antidote to fear."],
  ["做，胜过完美的计划。", "Doing beats a perfect plan."],
  ["完成比完美重要。", "Done is better than perfect."],
  ["先开始，再优化。", "Start first, then improve."],
  ["小行动带来大改变。", "Small actions bring big change."],
  ["每天进步1%，一年后你会进步37倍。", "Improve 1% each day and you will be 37 times better in a year."],
  ["习惯的力量超乎想象。", "The power of habit exceeds imagination."],
  ["好的习惯是未来的投资。", "Good habits are an investment in your future."],
  ["你的日常决定你的未来。", "Your daily routine determines your future."],
  ["微习惯，大改变。", "Tiny habits, big change."],
  ["坚持比强度重要。", "Consistency matters more than intensity."],
  ["持之以恒是关键。", "Perseverance is the key."],
  ["你的自律给你自由。", "Your discipline gives you freedom."],
  ["延迟满足是成功的关键。", "Delayed gratification is key to success."],
  ["耐心是一种超能力。", "Patience is a superpower."],
  ["等待也是一种行动。", "Waiting is also a form of action."],
  ["相信时间的力量。", "Trust the power of time."],
  ["我思故我在。", "I think, therefore I am."],
  ["知识就是力量。", "Knowledge is power."],
  ["读万卷书，行万里路。", "Read ten thousand books and travel ten thousand miles."],
  ["业精于勤，荒于嬉。", "Excellence comes from diligence; idleness leads to ruin."],
  ["行成于思，毁于随。", "Action succeeds through thought; failure follows recklessness."],
  ["书山有路勤为径，学海无涯苦作舟。", "Diligence is the path up the mountain of books; effort is the boat on the boundless sea of learning."],
  ["落红不是无情物，化作春泥更护花。", "Fallen blossoms are not heartless — they nourish spring soil to protect new flowers."],
  ["江山代有才人出，各领风骚数百年。", "Each age brings forth its talents, each leading their era for centuries."],
  ["千磨万击还坚劲，任尔东西南北风。", "Through countless blows it stands firm, whatever wind blows from any direction."],
  ["些小吾曹州县吏，一枝一叶总关情。", "Though we are humble county officials, every branch and leaf touches our hearts."],
  ["你的学习能力很强。", "You are a strong learner."],
  ["犯错是学习的一部分。", "Mistakes are part of learning."],
  ["失败是反馈，不是终点。", "Failure is feedback, not the finish line."],
  ["从错误中吸取教训。", "Learn from your mistakes."],
  ["每一次失败都让你更接近成功。", "Every failure brings you closer to success."],
  ["你的复原力令人钦佩。", "Your resilience is admirable."],
  ["跌倒后站起来的样子很美。", "There is beauty in rising after a fall."],
  ["挫折是成长的养分。", "Setbacks are nourishment for growth."],
  ["你的经历塑造了你的智慧。", "Your experiences have shaped your wisdom."],
  ["痛苦会过去，智慧会留下。", "Pain will pass; wisdom will remain."],
  ["你的伤疤是你的勋章。", "Your scars are your medals."],
  ["经历过黑暗，你更懂光明。", "Having known darkness, you understand light more deeply."],
  ["你的故事能激励他人。", "Your story can inspire others."],
  ["分享你的经历，帮助他人。", "Share your experience to help others."],
  ["你的痛苦不是白费的。", "Your pain was not in vain."],
  ["把痛苦转化为力量。", "Transform pain into strength."],
  ["你的韧性是榜样。", "Your resilience is an example to others."],
  ["你比困难更强大。", "You are stronger than your difficulties."],
  ["没有过不去的坎。", "There is no obstacle you cannot overcome."],
  ["这一切都会过去。", "This too shall pass."],
  ["生活就像骑自行车，想保持平衡就得往前走。", "Life is like riding a bicycle — to keep your balance you must keep moving."],
  ["想象力比知识更重要。", "Imagination is more important than knowledge."],
  ["不要努力成为成功的人，而要努力成为有价值的人。", "Try not to become a person of success, but rather try to become a person of value."],
  ["逻辑会带你从A到B，想象力会带你去任何地方。", "Logic will get you from A to B. Imagination will take you everywhere."],
  ["在困难中蕴藏着机会。", "In the middle of difficulty lies opportunity."],
  ["人生就像一盒巧克力，你永远不知道下一颗是什么味道。", "Life is like a box of chocolates — you never know what you're gonna get."],
  ["愚蠢的人做愚蠢的事，聪明人从愚蠢的事中学习。", "Stupid is as stupid does."],
  ["奇迹每天都在发生。", "Miracles happen every day."],
  ["相信奇迹，你就是奇迹。", "Believe in miracles — you are one."],
  ["你的潜力无限。", "Your potential is limitless."],
  ["别给自己设限。", "Do not limit yourself."],
  ["可能性比你想象的多。", "There are more possibilities than you imagine."],
  ["保持开放的心态。", "Keep an open mind."],
  ["新体验带来新成长。", "New experiences bring new growth."],
  ["尝试新事物。", "Try new things."],
  ["走出舒适区。", "Step outside your comfort zone."],
  ["成长发生在舒适区之外。", "Growth happens outside your comfort zone."],
  ["冒险是值得的。", "Adventure is worth it."],
  ["勇气不是没有恐惧，而是带着恐惧前行。", "Courage is not the absence of fear, but moving forward despite it."],
  ["你的勇敢令人敬佩。", "Your bravery is admirable."],
  ["每一次尝试都是胜利。", "Every attempt is a victory."],
  ["你值得为自己骄傲。", "You deserve to be proud of yourself."],
  ["庆祝你的每一个成就。", "Celebrate every achievement."],
  ["小胜利也值得庆祝。", "Small wins deserve celebration too."],
  ["你的进步看得见。", "Your progress is visible."],
  ["肯定自己的努力。", "Acknowledge your own effort."],
  ["你是自己最好的啦啦队。", "You are your own best cheerleader."],
  ["为自己加油。", "Cheer yourself on."],
  ["你正在创造美好。", "You are creating something beautiful."],
  ["未来可期。", "The future holds promise."],
  ["人的一切痛苦，本质上都是对自己无能的愤怒。", "All human suffering is, at bottom, anger at one's own inadequacy."],
  ["生活是一个缓慢受锤的过程。", "Life is a process of being slowly hammered into shape."],
  ["一个人只拥有此生此世是不够的，他还应该拥有诗意的世界。", "A person needs not only this life but also a poetic world."],
  ["那一天我二十一岁，在我一生的黄金时代。", "That day I was twenty-one, in the golden age of my life."],
  ["我要爱，想吃，还想在一瞬间变成天上半明半暗的云。", "I want to love, to eat, and in an instant to become a half-lit cloud in the sky."],
  ["我们活在世上，不免要承担各种责任，但别忘了对自己负一点责任。", "We bear many responsibilities in life, but do not forget a little responsibility to yourself."],
  ["幸福不是得到的多，而是计较的少。", "Happiness is not having more, but wanting less."],
  ["知足常乐。", "Contentment brings lasting joy."],
  ["感恩你所拥有的。", "Be grateful for what you have."],
  ["每天找三件值得感恩的事。", "Find three things to be grateful for each day."],
  ["感恩的心态带来幸福的生活。", "A grateful heart leads to a happy life."],
  ["你的感恩清单会越来越长。", "Your gratitude list will keep growing."],
  ["关注拥有的，而不是缺失的。", "Focus on what you have, not what you lack."],
  ["富足是一种心态。", "Abundance is a mindset."],
  ["你已经有足够多了。", "You already have enough."],
  ["当下就是最珍贵的。", "The present moment is the most precious."],
  ["此刻就是你拥有的全部。", "This moment is all you truly have."],
  ["正念生活，感受当下。", "Live mindfully; feel the present."],
  ["呼吸，就在此刻。", "Breathe — right here, right now."],
  ["你的呼吸是你最好的锚。", "Your breath is your best anchor."],
  ["回到当下，回到呼吸。", "Return to the present; return to your breath."],
  ["此刻的你已经足够好。", "You, right now, are already enough."],
  ["不需要更多，此刻就完整。", "You need nothing more — you are whole in this moment."],
  ["平静就在你内心。", "Peace is within you."],
  ["你的内在有无尽的资源。", "You have endless resources within."],
  ["向内寻找答案。", "Look inward for answers."],
  ["你的直觉值得信任。", "Your intuition is worth trusting."],
  ["倾听内心的声音。", "Listen to your inner voice."],
  ["你知道什么对你最好。", "You know what is best for you."],
  ["相信你的内在智慧。", "Trust your inner wisdom."],
  ["真正的发现之旅不在于寻找新的风景，而在于拥有新的眼睛。", "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes."],
  ["生命短暂，艺术长存。", "Life is short, art is long."],
  ["认识你自己。", "Know thyself."],
  ["未经审视的人生不值得过。", "The unexamined life is not worth living."],
  ["我知道我一无所知。", "I know that I know nothing."],
  ["美德即知识。", "Virtue is knowledge."],
  ["人是万物的尺度。", "Man is the measure of all things."],
  ["存在先于本质。", "Existence precedes essence."],
  ["他人即地狱。", "Hell is other people."],
  ["你的选择定义了你。", "Your choices define you."],
  ["你有选择的自由。", "You have the freedom to choose."],
  ["即使在限制中，你也有选择的余地。", "Even within limits, you still have room to choose."],
  ["选择你的态度。", "Choose your attitude."],
  ["态度决定一切。", "Attitude is everything."],
  ["你的视角创造你的现实。", "Your perspective creates your reality."],
  ["换个角度看问题。", "Look at the problem from another angle."],
  ["重构你的叙事。", "Reframe your narrative."],
  ["你是自己故事的作者。", "You are the author of your own story."],
  ["重写你的故事。", "Rewrite your story."],
  ["过去不定义你。", "The past does not define you."],
  ["你可以重新开始。", "You can start again."],
  ["每一天都是新的篇章。", "Every day is a new chapter."],
  ["你的故事由你书写。", "Your story is yours to write."],
  ["创造你想要的生活。", "Create the life you want."],
  ["你是自己生活的建筑师。", "You are the architect of your life."],
  ["设计你的人生。", "Design your life."],
  ["有意识地生活。", "Live with intention."],
  ["活出你的意图。", "Live out your intentions."],
  ["你的生命是有目的的。", "Your life has purpose."],
  ["成功不是终点，失败也不是终结，唯有勇气才是永恒。", "Success is not final, failure is not fatal: it is the courage to continue that counts."],
  ["永不放弃，永不放弃，永不放弃。", "Never give in, never give in, never give in."],
  ["悲观者在机会中看到困难，乐观者在困难中看到机会。", "A pessimist sees difficulty in every opportunity; an optimist sees opportunity in every difficulty."],
  ["我们靠所得来谋生，靠给予来创造生活。", "We make a living by what we get, but we make a life by what we give."],
  ["成功就是从一个失败走到另一个失败，却不失去热情。", "Success is going from failure to failure without loss of enthusiasm."],
  ["你的热情是你的指南针。", "Your passion is your compass."],
  ["追随你的热情。", "Follow your passion."],
  ["做你热爱的事。", "Do what you love."],
  ["热爱你所做的事。", "Love what you do."],
  ["激情驱动卓越。", "Passion drives excellence."],
  ["你的热情感染他人。", "Your passion inspires others."],
  ["保持好奇心。", "Stay curious."],
  ["永远不要停止学习。", "Never stop learning."],
  ["成长是一生的旅程。", "Growth is a lifelong journey."],
  ["你永远是学生。", "You are always a student."],
  ["保持谦逊。", "Stay humble."],
  ["谦逊让你走得更远。", "Humility takes you further."],
  ["开放的心态带来新的可能。", "An open mind brings new possibilities."],
  ["愿意被改变。", "Be willing to be changed."],
  ["灵活性是力量。", "Flexibility is strength."],
  ["适应变化。", "Adapt to change."],
  ["变化是唯一的常量。", "Change is the only constant."],
  ["拥抱变化。", "Embrace change."],
  ["在变化中找到机会。", "Find opportunity in change."],
  ["变化带来成长。", "Change brings growth."],
  ["不要问国家能为你做什么，问你能为国家做什么。", "Ask not what your country can do for you — ask what you can do for your country."],
  ["梦想那些你从未敢梦想的，成为那些你从未敢成为的。", "Dream the dreams you never dared to dream; become what you never dared to become."],
  ["做最好的自己，因为没有人能比你做得更好。", "Be the best version of yourself — no one can do that better than you."],
  ["把你的伤口变成智慧。", "Turn your wounds into wisdom."],
  ["你的人生是你创造的。", "Your life is what you make it."],
  ["相信你自己，创造属于你的奇迹。", "Believe in yourself and create your own miracle."],
  ["奇迹始于信念。", "Miracles begin with belief."],
  ["相信是看见的第一步。", "Believing is the first step to seeing."],
  ["你的信念创造你的现实。", "Your beliefs create your reality."],
  ["保持信念。", "Hold on to your faith."],
  ["希望在心中。", "Hope lives in the heart."],
  ["希望是力量的源泉。", "Hope is a source of strength."],
  ["永远不要失去希望。", "Never lose hope."],
  ["希望之光永不熄灭。", "The light of hope never goes out."],
  ["你的希望感染他人。", "Your hope inspires others."],
  ["传递希望。", "Pass on hope."],
  ["你是他人的光。", "You are a light for others."],
  ["照亮他人的路。", "Light the way for others."],
  ["你的善良改变世界。", "Your kindness changes the world."],
  ["善良是一种选择。", "Kindness is a choice."],
]);

export const enAuthorByZhAuthor = new Map([
  ["乔丹·彼得森", "Jordan Peterson"],
  ["李白", "Li Bai"],
  ["维维安·格林", "Vivian Greene"],
  ["海明威《老人与海》", "Ernest Hemingway (The Old Man and the Sea)"],
  ["雪莱", "Percy Bysshe Shelley"],
  ["《肖申克的救赎》", "The Shawshank Redemption"],
  ["罗曼·罗兰", "Romain Rolland"],
  ["尼采", "Friedrich Nietzsche"],
  ["《尚书》", "Book of Documents"],
  ["《周易》", "Book of Changes (I Ching)"],
  ["荀子", "Xunzi"],
  ["老子", "Laozi"],
  ["杜甫", "Du Fu"],
  ["刘禹锡", "Liu Yuxi"],
  ["陆游", "Lu You"],
  ["《警世贤文》", "Admonitions for the World"],
  ["黄檗禅师", "Huangbo Xiyun"],
  ["王之涣", "Wang Zhihuan"],
  ["王勃", "Wang Bo"],
  ["高适", "Gao Shi"],
  ["范仲淹", "Fan Zhongyan"],
  ["文天祥", "Wen Tianxiang"],
  ["于谦", "Yu Qian"],
  ["林则徐", "Lin Zexu"],
  ["张载", "Zhang Zai"],
  ["屈原", "Qu Yuan"],
  ["孔子", "Confucius"],
  ["笛卡尔", "René Descartes"],
  ["培根", "Francis Bacon"],
  ["董其昌", "Dong Qichang"],
  ["韩愈", "Han Yu"],
  ["龚自珍", "Gong Zizhen"],
  ["赵翼", "Zhao Yi"],
  ["郑板桥", "Zheng Banqiao"],
  ["爱因斯坦", "Albert Einstein"],
  ["《阿甘正传》", "Forrest Gump"],
  ["王小波", "Wang Xiaobo"],
  ["普鲁斯特", "Marcel Proust"],
  ["希波克拉底", "Hippocrates"],
  ["苏格拉底", "Socrates"],
  ["普罗泰戈拉", "Protagoras"],
  ["萨特", "Jean-Paul Sartre"],
  ["丘吉尔", "Winston Churchill"],
  ["肯尼迪", "John F. Kennedy"],
  ["奥普拉", "Oprah Winfrey"],
]);
